### ISSUE TITLE
NPE when loading world

### ISSUE THREAD

**Issue by Daquesha** [Yeregorix/Mirage#20]
First installing the plugin, I get greeted with the message:
"To change the enabled/disabled state of any bStats use in a plugin (mirage and economylite), visit the Sponge config"

Not sure if this has anything to do with the effectiveness of the plugin but Idk what it's for

Mirage continues to load the resources as fine. When interacting with different worlds/dimensions, the regular world seems to be okay with no errors, but other/modded dimensions get:

Failed to load configuration for world (ex: DIM-4)
java.lang.NullPointerException: null
at net.smoofyuniverse.mirage.impl.network.NetworkWorld.loadConfig(NetworkWorld.java:140) ~[NetworkWorld.class:?]
at net.minecraft.world.WorldServer.handler$onInit$bbe000(WorldServer.java:4534) [oo.class:?]
at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:174) [oo.class:?] at org.spongepowered.common.world.WorldManager.createWorldFromProperties(WorldManager.java:803) [WorldManager.class:1.12.2-2768-7.1.5] at org.spongepowered.common.world.WorldManager.loadAllWorlds(WorldManager.java:771) [WorldManager.class:1.12.2-2768-7.1.5] at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:3545) [MinecraftServer.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) [nz.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?] at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]

Then from here no changes in config have no effect.

Using latest Mirage, sponge, and projectcore

Today now crashes the server when someone attempts to xray giving:

[Mirage]: Failed to load a network chunk from cache
java.lang.NullPointerException: null
at net.smoofyuniverse.mirage.impl.network.NetworkBlockContainer.setDataFromNBT(NetworkBlockContainer.java:323) ~[NetworkBlockContainer.class:?] at net.smoofyuniverse.mirage.impl.network.NetworkBlockContainer.load(NetworkBlockContainer.java:308) ~[NetworkBlockContainer.class:?] at net.smoofyuniverse.mirage.impl.network.NetworkChunk.load(NetworkChunk.java:241) ~[NetworkChunk.class:?] at net.smoofyuniverse.mirage.impl.network.NetworkChunk.loadFromCacheNow(NetworkChunk.java:229) ~[NetworkChunk.class:?] at net.minecraft.world.chunk.Chunk.handler$onSetStorageArrays$bbc000(Chunk.java:5845) [axw.class:?] at net.minecraft.world.chunk.Chunk.func_76602_a(Chunk.java:1137) [axw.class:?] at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75823_a(AnvilChunkLoader.java:463) [aye.class:?] at net.minecraft.world.chunk.storage.AnvilChunkLoader.checkedReadChunkFromNBT__Async(AnvilChunkLoader.java:128) [aye.class:?] at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadChunk__Async(AnvilChunkLoader.java:92) [aye.class:?] at net.minecraftforge.common.chunkio.ChunkIOProvider.run(ChunkIOProvider.java:70) [ChunkIOProvider.class:?] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_192]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_192]
at java.lang.Thread.run(Thread.java:813) [?:1.8.0_192]

**Comment by Yeregorix** [comment]
The issues your having are really strange. I will investigate on it and keep you updated.
Can you send me (here or in private) an archive of a server with the minimum to reproduce your issue ? For example just the mods and the affected worlds. This would help me a lot to reproduce your issue on my side and thus to fix it.
Also, can you give me a copy of your full log (logs/fml-server-latest.log) using a service such as pastebin.com ?

**Comment by Daquesha** [comment]
I'll message you a .zip of the current server setup that doesn't work. My assumption is a wack mod or too many mods screwing up with it. If it works for you I'd be very surprised

**Comment by Yeregorix** [comment]
Do you have Discord ? If so contact me, here is my id: Yeregorix#7426

**Comment by EpicSimplyEpic** [comment]
Your discord doesn’t allow new friend requests to come in

**Comment by Daquesha** [comment]
Your discord doesn't allow incoming friend requests

**Comment by Yeregorix** [comment]
Sorry, I wasn't aware of that ^^' It's should okay now

**Comment by Yeregorix** [comment]
Please try the latest version and send me the logs with a service such as [pastebin](https://pastebin.com/).

**Comment by megoesrawr** [comment]
https://pastebin.com/gg5BdKES I get this error on the newest Mirage AKA 1.3.9

**Comment by Yeregorix** [comment]
@megoesrawr Please open a separate issue. Your error has nothing to do with this one.
