### ISSUE TITLE
Fake blocks appear on the client

### ISSUE THREAD

**Issue by MikasaPixelmon** [Yeregorix/Mirage#46]
Sometimes when you go all down, there's this weird visual blocks where you can mine thru visual bedrock and
no1 else sees it but sometimes it happens to different people too.

I just received this report by a player and this is the video (gif) he added in #bug-issues 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/69644328/90325043-dc194500-df76-11ea-9543-151c8ca64f92.gif)

**Comment by GranTesoro86** [comment]
I have the same problem
Can this be solved? @Yeregorix 

https://gyazo.com/5b61c20355242c491c2586f94724717e

**Comment by Yeregorix** [comment]
I will take a look as soon as possible! Since when this issue is happening? Also, can you both send me logs?

**Comment by GranTesoro86** [comment]
[latest.log](https://github.com/Yeregorix/Mirage/files/5080395/latest.log)
Not sure if it is this 
```[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: java.io.IOException: Stream Closed
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at java.io.RandomAccessFile.length(Native Method)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at net.minecraft.world.chunk.storage.RegionFile.func_76706_a(RegionFile.java:279)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at net.minecraft.world.chunk.storage.RegionFile$ChunkBuffer.close(RegionFile.java:361)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:241)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at net.smoofyuniverse.mirage.impl.network.NetworkWorld.saveToCache(NetworkWorld.java:328)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at net.smoofyuniverse.mirage.impl.network.NetworkWorld.savePendingChunk(NetworkWorld.java:316)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.handler$bbm000$onWriteChunkData(AnvilChunkLoader.java:1777)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_183013_b(AnvilChunkLoader.java:244)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75814_c(AnvilChunkLoader.java:1470)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at net.minecraft.world.storage.ThreadedFileIOBase.func_75736_b(SourceFile:37)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at net.minecraft.world.storage.ThreadedFileIOBase.run(SourceFile:30)
[17:26:25] [File IO Thread/INFO] [STDERR]: [net.minecraft.world.chunk.storage.RegionFile:func_76706_a:298]: 	at java.lang.Thread.run(Thread.java:748)```

**Comment by MikasaPixelmon** [comment]
It happens in many versions of mirages, I never understand why so many people haven't reported it yet, haha. I think it's because no one really has a github account yet, which is why there aren't as many problem reports. Maybe you should open a Discord @Yeregorix  server which helps a lot. I could definitely also moderate the chat for you if possible 👍

**Comment by MikasaPixelmon** [comment]
This is me doing it, but it doesn't give any errors in the console
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/69644328/90332159-fc6af300-dfba-11ea-9941-05a2bf9d7179.gif)
Also don't mind the big error above, that's just spam happening by DayCare plugin.

**Comment by Yeregorix** [comment]
I will think about Discord when I get the time, for now I will focus on this issue.

**Comment by Yeregorix** [comment]
I did few simple tests on naturally generated ores and bedrock on both SF 7.2.2 and SF latest and the issue didn't happened. Are you experiencing the issue constantly and for all ores/bedrock or just sometimes or under specific circumstances? Also, it might be specific to your installation. If someone can send me an archive with a minimal server setup that has this issue it would help me a lot to reproduce it. An archive containing mods jars and configs is generally sufficient but I can't guarantee anything before I can reproduce the issue on my side. Being able to reproduce the issue is the first step for me to be able to fix it.

**Comment by MikasaPixelmon** [comment]
What's your discord username. Can you send me that private on github.

**Comment by Yeregorix** [comment]
There is no PM on Github, that's why I suggested other options. Just go to Sponge's forums or Sponge's discord and you will find me.

**Comment by Yeregorix** [comment]
I succeeded to reproduce the issue on my side on both SpongeForge and SpongeVanilla 🙂. It sounds like a server/client desynchronization as the issue disappear when the player disconnect then reconnect. I've also found that the issue happens in chunk containers (16x16x16). I keep investigating.

**Comment by Yeregorix** [comment]
I'm getting busy these days, I keep working on this issue but it will take longer than expected.

**Comment by MikasaPixelmon** [comment]
I really look forward for it, when it get's fixed :D

**Comment by Yeregorix** [comment]
I think I finally found what's causing this issue. When a internal container resizes his palette it causes a full deobfuscation of the network container without send updates to the client. I will work on a fix soon. 🙂
